# Generated by Django 4.1.2 on 2022-10-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.CharField(max_length=100)),
                ("sensor_name", models.CharField(max_length=100)),
                (
                    "sensor_type",
                    models.IntegerField(
                        choices=[
                            [1, "TEMPERATURE_SENSOR"],
                            [2, "PRESSURE_SENSOR"],
                            [3, "HUMIDITY_SENSOR"],
                            [4, "FLUID_SENSOR"],
                            [5, "PIEZO_SENSOR"],
                        ]
                    ),
                ),
                ("sensor_value", models.CharField(max_length=100)),
                ("sensor_data", models.CharField(max_length=100)),
            ],
        ),
    ]
