# Generated by Django 4.1.2 on 2022-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="sensor_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="sensor_type",
            field=models.IntegerField(
                choices=[
                    (1, "TEMPERATURE_SENSOR"),
                    (2, "PRESSURE_SENSOR"),
                    (3, "HUMIDITY_SENSOR"),
                    (4, "FLUID_SENSOR"),
                    (5, "PIEZO_SENSOR"),
                ]
            ),
        ),
    ]
